name: Update disposable email domains

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  update_domains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Get current domains.json
        run: |
          echo "Current domains.json:"
          cat domains.json

      - name: Get latest domains.json
        id: get-latest-domains
        run: |
          set -e
          curl -s https://raw.githack.com/disposable/disposable-email-domains/master/domains.json > latest-domains.json
          echo "Latest domains.json:"
          cp latest-domains.json domains.json
          echo "Updated domains.json"
          npm version patch -m "Bump version to %s"

      - name: Bump version and publish package
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}