name: Update

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  update_domains:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.compare-domains.outputs.changed }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/

      - name: Get current domains.json
        run: |
          echo "Current domains.json:"
          cat domains.json

      - name: Get latest domains.json
        id: get-latest-domains
        run: |
          set -e
          curl -s https://raw.githack.com/disposable/disposable-email-domains/master/domains.json > latest-domains.json
          echo "Latest domains.json:"
          cat latest-domains.json

      - name: Compare domains.json files
        id: compare-domains
        run: |
          if diff -q domains.json latest-domains.json; then
            echo "No changes in domains.json"
            echo "{changed}={false}" >> $GITHUB_OUTPUT
          else
            cp latest-domains.json domains.json
            echo "Updated domains.json"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Bump version"
            git tag -a "Bump version to v${{ env.npm_package_version }}" -m "Bump version to v${{ env.npm_package_version }}"
            npm version patch -m "Bump version to %s"
            git push
            npm publish --access public --registry=https://npm.package.github.com/
          fi

      - name: Bump version and publish package  
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
        if: ${{ steps.compare-domains.outputs.changed }} == 'true'
