name: Update disposable email domains

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  update_domains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Get current domains.json
        run: |
          echo "Current domains.json:"
          cat domains.json

      - name: Get latest domains.json
        id: get-latest-domains
        run: |
          set -e
          curl -s https://raw.githack.com/disposable/disposable-email-domains/master/domains.json > latest-domains.json
          echo "Latest domains.json:"
          cat latest-domains.json
          echo "::set-output name=changed::$(cmp --silent domains.json latest-domains.json || echo true)"

      - name: Check if domains.json changed
        run: |
          if [ "${{ steps.get-latest-domains.outputs.changed }}" = "false" ]; then
            echo "Domains.json changed"
          else
            echo "Domains.json not changed"
            exit 1
          fi

      - name: Update domains.json
        if: steps.get-latest-domains.outputs.changed == 'true'
        run: |
          cp latest-domains.json domains.json
          echo "Updated domains.json"

      - name: Bump version and publish package
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
          tag: 'latest'
          directory: '.'
          version: 'patch'
